### ISSUE TITLE
Install on Debian 9

### ISSUE THREAD

**Issue by jbelien** [itinero/routing-api#7]
Hi,

I tried to install `routing-api` on a Debian 9 server.
No problem to install .NET core following https://www.microsoft.com/net/core#linuxdebian

But when I execute `./build.sh`, here is the error I have (see hereunder).
Unfortunately, I not used enough to .NET to know how can I fix it. Could you help me ?

Thanks

```

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
  Restoring packages for /home/debian/routing-api/src/Itinero.API/Itinero.API.csproj...
  Installing System.Runtime.Handles 4.0.0.
  Installing System.Xml.XPath 4.0.1.
  Installing Microsoft.AspNetCore.Http.Extensions 1.0.0.
  Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.0.
  Installing Microsoft.Net.Http.Headers 1.0.0.
  Installing Microsoft.AspNetCore.DataProtection.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Cryptography.Internal 1.0.0.
  Installing Microsoft.Extensions.Localization.Abstractions 1.0.0.
  Installing System.IO.FileSystem 4.0.0.
  Installing System.Runtime.InteropServices 4.0.20.
  Installing System.IO.FileSystem.Primitives 4.0.0.
  Installing Microsoft.NETCore.Jit 1.0.2.
  Installing System.Xml.XPath.XDocument 4.0.1.
  Installing System.Text.Encoding.CodePages 4.0.1.
  Installing System.Diagnostics.FileVersionInfo 4.0.0.
  Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
  Installing Microsoft.NETCore.DotNetHost 1.0.1.
  Installing Microsoft.AspNetCore.Routing 1.0.0.
  Installing Microsoft.AspNetCore.Mvc.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Authorization 1.0.0.
  Installing Microsoft.AspNetCore.Http 1.0.0.
  Installing Microsoft.AspNetCore.DataProtection 1.0.0.
  Installing Microsoft.Extensions.ObjectPool 1.0.0.
  Installing Microsoft.AspNetCore.WebUtilities 1.0.0.
  Installing Microsoft.Extensions.Localization 1.0.0.
  Installing Microsoft.AspNetCore.JsonPatch 1.0.0.
  Installing Microsoft.Extensions.Options 1.0.0.
  Installing System.Xml.ReaderWriter 4.0.10.
  Installing System.Runtime.InteropServices 4.0.0.
  Installing Microsoft.Extensions.Logging.Console 1.0.2.
  Installing Nancy 2.0.0-barneyrubble.
  Installing Microsoft.Extensions.Configuration.Json 1.0.2.
  Installing Itinero 1.3.0.
  Installing Microsoft.Extensions.Configuration.FileExtensions 1.0.2.
  Installing Itinero.Transit 0.3.4-alpha.
  Installing Itinero.IO.Osm 1.3.0.
  Installing Microsoft.AspNetCore.Owin 1.0.2.
  Installing Microsoft.AspNetCore.Server.IISIntegration 1.0.2.
  Installing Microsoft.AspNetCore.Diagnostics 1.0.2.
  Installing Microsoft.AspNetCore.Server.Kestrel 1.0.3.
  Installing Microsoft.ApplicationInsights.AspNetCore 1.0.0.
  Installing Microsoft.NETCore.App 1.1.1.
  Installing System.Console 4.0.0.
  Installing System.Threading 4.0.11.
  Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
  Installing Microsoft.Extensions.Logging.Abstractions 1.0.2.
  Installing Microsoft.Extensions.Configuration.Abstractions 1.0.2.
  Installing System.Dynamic.Runtime 4.0.11.
  Installing System.Runtime.Serialization.Primitives 4.1.1.
  Installing System.IO.FileSystem 4.0.1.
  Installing Newtonsoft.Json 9.0.1.
  Installing Microsoft.Extensions.Configuration 1.0.2.
  Installing System.AppContext 4.1.0.
  Installing System.Reflection.Primitives 4.0.0.
  Installing Microsoft.Extensions.FileProviders.Physical 1.0.1.
  Installing Microsoft.CSharp 4.0.1.
  Installing System.Collections.Concurrent 4.0.12.
  Installing System.Resources.ResourceManager 4.0.0.
  Installing System.Diagnostics.Tools 4.0.1.
  Installing System.IO 4.1.0.
  Installing System.Linq 4.1.0.
  Installing System.Net.Primitives 4.0.11.
  Installing System.Reflection.Extensions 4.0.1.
  Installing System.Reflection.TypeExtensions 4.1.0.
  Installing System.Runtime 4.1.0.
  Installing System.Security.Cryptography.Algorithms 4.2.0.
  Installing System.Security.Cryptography.X509Certificates 4.1.0.
  Installing System.Net.Primitives 4.0.0.
  Installing System.Net.WebSockets 4.0.0.
  Installing Microsoft.Extensions.Primitives 1.0.0.
  Installing Microsoft.AspNetCore.Http.Features 1.0.2.
  Installing System.Diagnostics.Contracts 4.0.1.
  Installing System.Text.RegularExpressions 4.1.0.
  Installing System.Threading.Thread 4.0.0.
  Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2.
  Installing Microsoft.Extensions.PlatformAbstractions 1.0.0.
  Installing System.Xml.XmlSerializer 4.0.11.
  Installing System.Net.NameResolution 4.0.0.
  Installing System.Collections.Specialized 4.0.1.
  Installing System.Security.Claims 4.0.1.
  Installing System.Data.Common 4.1.0.
  Installing Microsoft.Extensions.DependencyModel 1.0.0.
  Installing System.ComponentModel.TypeConverter 4.1.0.
  Installing NETStandard.Library 1.6.0.
  Installing System.Reflection 4.1.0.
  Installing Reminiscence 1.0.5.
  Installing runtime.native.System.IO.Compression 4.1.0.
  Installing Microsoft.CodeAnalysis.Common 1.3.0.
  Installing GTFS 2.0.1-alpha.
  Installing OsmSharp 5.0.7.
  Installing Microsoft.AspNetCore.Http 1.0.2.
  Installing Microsoft.AspNetCore.HttpOverrides 1.0.2.
  Installing System.Security.Principal.Windows 4.0.0.
  Installing Microsoft.Extensions.Options 1.0.2.
  Installing Microsoft.AspNetCore.Hosting.Abstractions 1.0.2.
  Installing Microsoft.AspNetCore.Http.Extensions 1.0.2.
  Installing System.Diagnostics.DiagnosticSource 4.0.0.
  Installing System.Reflection.Metadata 1.3.0.
  Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
  Installing runtime.native.System.Net.Security 4.0.1.
  Installing System.Threading.Overlapped 4.0.1.
  Installing Microsoft.NETCore.Jit 1.0.6.
  Installing Microsoft.NETCore.Windows.ApiSets 1.0.1.
  Installing Microsoft.Win32.Registry 4.0.0.
  Installing Microsoft.AspNetCore.Mvc.Core 1.0.0.
  Installing Microsoft.AspNetCore.Antiforgery 1.0.0.
  Installing Microsoft.AspNetCore.Mvc.DataAnnotations 1.0.0.
  Installing Microsoft.AspNetCore.Mvc.Formatters.Json 1.0.0.
  Installing Microsoft.Extensions.WebEncoders 1.0.0.
  Installing Microsoft.AspNetCore.Html.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Diagnostics.Abstractions 1.0.0.
  Installing System.Xml.XDocument 4.0.10.
  Installing System.IO.Compression 4.0.0.
  Installing System.Reflection 4.0.10.
  Installing System.Runtime 4.0.20.
  Installing System.Text.RegularExpressions 4.0.10.
  Installing System.Diagnostics.StackTrace 4.0.1.
  Installing Microsoft.AspNetCore.WebUtilities 1.0.2.
  Installing Microsoft.AspNetCore.Diagnostics.Abstractions 1.0.2.
  Installing System.Diagnostics.Debug 4.0.11.
  Installing System.Collections 4.0.11.
  Installing System.Globalization 4.0.11.
  Installing System.Runtime.Extensions 4.1.0.
  Installing System.Runtime.InteropServices 4.1.0.
  Installing System.Linq 4.0.0.
  Installing System.Text.Encoding 4.0.11.
  Installing System.Net.Http 4.0.0.
  Installing System.Threading.Tasks 4.0.11.
  Installing System.IO 4.0.10.
  Installing System.Threading.ThreadPool 4.0.10.
  Installing System.Threading.Timer 4.0.1.
  Installing System.Buffers 4.0.0.
  Installing System.Globalization 4.0.10.
  Installing System.Threading.Tasks.Extensions 4.0.0.
  Installing System.Numerics.Vectors 4.1.1.
  Installing Libuv 1.9.0.
  Installing Microsoft.AspNetCore.Hosting 1.0.2.
  Installing Microsoft.Extensions.Logging.Abstractions 1.0.0.
  Installing Microsoft.Extensions.DiagnosticAdapter 1.0.0.
  Installing Microsoft.Extensions.Configuration 1.0.0.
  Installing Microsoft.AspNetCore.Http.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Hosting.Abstractions 1.0.0.
  Installing Microsoft.ApplicationInsights 2.1.0.
  Installing Microsoft.AspNetCore.Mvc.ViewFeatures 1.0.0.
  Installing Microsoft.NETCore.Platforms 1.0.2.
  Installing System.Diagnostics.Process 4.1.0.
  Installing System.Collections.Immutable 1.2.0.
  Installing System.Globalization.Extensions 4.0.1.
  Installing System.Linq.Expressions 4.1.0.
  Installing System.Linq.Parallel 4.0.1.
  Installing System.Linq.Queryable 4.0.1.
  Installing System.Resources.Reader 4.0.0.
  Installing System.Runtime.Loader 4.0.0.
  Installing System.Security.Cryptography.Encoding 4.0.0.
  Installing System.Diagnostics.Tracing 4.0.20.
  Installing System.Security.Cryptography.Primitives 4.0.0.
  Installing System.Threading.Tasks.Dataflow 4.6.0.
  Installing Libuv 1.9.1.
  Installing System.Reflection.DispatchProxy 4.0.1.
  Installing System.ComponentModel.Annotations 4.1.0.
  Installing System.Runtime.Extensions 4.0.10.
  Installing System.IO.MemoryMappedFiles 4.0.0.
  Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.6.
  Installing System.Net.WebHeaderCollection 4.0.1.
  Installing System.ComponentModel 4.0.1.
  Installing System.IO.UnmanagedMemoryStream 4.0.1.
  Installing System.IO.FileSystem.Watcher 4.0.0.
  Installing System.Text.Encoding.Extensions 4.0.10.
  Installing System.Threading.Tasks.Parallel 4.0.1.
  Installing System.Net.Requests 4.0.11.
  Installing System.Net.Security 4.0.0.
  Installing Microsoft.NETCore.DotNetHostPolicy 1.0.3.
  Installing Microsoft.VisualBasic 10.0.1.
  Installing System.Net.Http 4.1.1.
  Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
  Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
  Installing Microsoft.NETCore.Platforms 1.0.1.
  Installing Microsoft.NETCore.Targets 1.0.1.
  Installing runtime.native.System 4.0.0.
  Installing System.Resources.ResourceManager 4.0.1.
  Installing Microsoft.Extensions.Primitives 1.0.1.
  Installing System.ObjectModel 4.0.12.
  Installing System.Reflection.Emit 4.0.1.
  Installing System.Reflection.Extensions 4.0.0.
  Installing System.Diagnostics.Debug 4.0.10.
  Installing System.Reflection.Emit.ILGeneration 4.0.1.
  Installing System.Reflection.Primitives 4.0.1.
  Installing System.IO.FileSystem.Primitives 4.0.1.
  Installing System.Text.Encoding 4.0.10.
  Installing System.Runtime.Handles 4.0.1.
  Installing System.Text.Encoding.Extensions 4.0.11.
  Installing System.Xml.ReaderWriter 4.0.11.
  Installing System.Collections 4.0.10.
  Installing System.Xml.XDocument 4.0.11.
  Installing Microsoft.Extensions.FileProviders.Abstractions 1.0.1.
  Installing System.Threading.Tasks 4.0.10.
  Installing Microsoft.Extensions.FileSystemGlobbing 1.0.1.
  Installing System.Diagnostics.Tracing 4.1.0.
  Installing runtime.native.System.Security.Cryptography 4.0.0.
  Installing System.Runtime.Numerics 4.0.1.
  Installing runtime.native.System.Net.Http 4.0.1.
  Installing System.Globalization.Calendars 4.0.1.
  Installing System.Security.Cryptography.Cng 4.2.0.
  Installing System.Security.Cryptography.Csp 4.0.0.
  Installing System.Security.Cryptography.OpenSsl 4.0.0.
  Installing System.Xml.XmlDocument 4.0.1.
  Installing System.Collections.NonGeneric 4.0.1.
  Installing System.Security.Principal 4.0.1.
  Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
  Installing System.ComponentModel.Primitives 4.1.0.
  Installing Microsoft.Win32.Primitives 4.0.1.
  Installing System.IO.Compression 4.1.0.
  Installing System.IO.Compression.ZipFile 4.0.1.
  Installing System.Net.Http 4.1.0.
  Installing System.Net.Sockets 4.1.0.
  Installing Microsoft.NETCore.Portable.Compatibility 1.0.1.
  Installing System.Threading 4.0.10.
  Installing protobuf-net 2.1.0.
  Installing Microsoft.Net.Http.Headers 1.0.2.
  Installing Microsoft.Extensions.ObjectPool 1.0.1.
  Installing Microsoft.AspNetCore.Http.Abstractions 1.0.2.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.2.
  Installing System.Linq.Expressions 4.1.1.
  Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.2.
  Installing System.Text.Encodings.Web 4.0.0.
  Installing Microsoft.Extensions.Configuration.EnvironmentVariables 1.0.2.
  Installing Microsoft.Extensions.DependencyInjection 1.0.2.
  Installing Microsoft.Extensions.Logging 1.0.2.
  Installing System.Reflection.Emit.Lightweight 4.0.1.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0.
  Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Http.Features 1.0.0.
  Installing Microsoft.Extensions.FileProviders.Abstractions 1.0.0.
  Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.0.
  Installing System.Diagnostics.Tools 4.0.0.
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.  [/home/debian/routing-api/Itinero.API.sln]
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605:  Itinero.API (>= 1.0.0) -> Itinero.Transit (>= 0.3.4-alpha) -> GTFS (>= 2.0.1-alpha) -> System.Reflection.TypeExtensions (>= 4.3.0)  [/home/debian/routing-api/Itinero.API.sln]
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605:  Itinero.API (>= 1.0.0) -> Itinero.Transit (>= 0.3.4-alpha) -> System.Reflection.TypeExtensions (>= 4.1.0) [/home/debian/routing-api/Itinero.API.sln]
  Generating MSBuild file /home/debian/routing-api/src/Itinero.API/obj/Itinero.API.csproj.nuget.g.props.
  Generating MSBuild file /home/debian/routing-api/src/Itinero.API/obj/Itinero.API.csproj.nuget.g.targets.
  Restore failed in 12.37 sec for /home/debian/routing-api/src/Itinero.API/Itinero.API.csproj.
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605:  Itinero.API (>= 1.0.0) -> Itinero.Transit (>= 0.3.4-alpha) -> GTFS (>= 2.0.1-alpha) -> System.Reflection.TypeExtensions (>= 4.3.0)
/home/debian/routing-api/src/Itinero.API/Itinero.API.csproj : error NU1605:  Itinero.API (>= 1.0.0) -> Itinero.Transit (>= 0.3.4-alpha) -> System.Reflection.TypeExtensions (>= 4.1.0)
```

**Comment by jbelien** [comment]
Probable fix ?

Run
```
dotnet add package System.Reflection.TypeExtensions
```
in `src/Itinero.API` directory.

**Comment by jbelien** [comment]
Other issue when I try to run `./run.sh` : 

```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Itinero.API -> /home/debian/routing-api/src/Itinero.API/bin/Debug/netcoreapp1.0/Itinero.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.26
Using launch settings from /home/debian/routing-api/src/Itinero.API/Properties/launchSettings.json...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.1.1'.
```

**EDIT:** Fixed by 6764461317934acf172d79b19fbdcaf03f8b06ee

**Comment by jbelien** [comment]
Error with `./run.sh` : 

```
$Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Itinero.API -> /home/debian/routing-api/src/Itinero.API/bin/Debug/netcoreapp2.0/Itinero.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.27
Using launch settings from /home/debian/routing-api/src/Itinero.API/Properties/launchSettings.json...
[Bootstrapper] information - Loading all routerdb's from path: /home/debian/routing-api/src/Itinero.API/data
[Bootstrapper] information - Loading instance belgium from: /home/debian/routing-api/src/Itinero.API/data/belgium.a.routerdb

Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Itinero.API.Program.Main(String[] args) in /home/debian/routing-api/src/Itinero.API/Program.cs:line 45
```

**Comment by jbelien** [comment]
Fix for `libuv` issue :
```
sudo apt-get install automake libtool
curl -sSL https://github.com/libuv/libuv/archive/v1.4.2.tar.gz | sudo tar zxfv - -C /usr/local/src
cd /usr/local/src/libuv-1.4.2
sudo sh autogen.sh
sudo ./configure
sudo make 
sudo make install
sudo rm -rf /usr/local/src/libuv-1.4.2 && cd ~/
sudo ldconfig
```

Information found here :
- https://github.com/dotnet/core/issues/701
- https://github.com/aspnet/Home/wiki/Getting-Started-Prerequisites-for-Debian,-Ubuntu-and-derivitives#get-libuv

Shouldn't be necessary to install the library manually ; issue is caused by mixing between 1.1 and 2.0.

**Comment by xivk** [comment]
Ok, thanks Jonathan.

I'll leave this issue open until I have the opportunity to test this on a fresh install.

**Comment by jbelien** [comment]
I try to install and run everything on Ubuntu 16.04 and indeed no issue whatsoever with `libuv` :)

**Comment by joined** [comment]
Tried to install and run on Ubuntu 17.10, same error as above with `libuv`:

```
$ ./run.sh
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core                                                                                                                                
Copyright (C) Microsoft Corporation. All rights reserved.                                                                            
                                                                                                                                                                                              
  Restoring packages for /[...]/routing-api/src/Itinero.API/Itinero.API.csproj...                                                                    
  Restore completed in 446.17 ms for /[...]/routing-api/src/Itinero.API/Itinero.API.csproj.                                                          
  Itinero.API -> /[...]/routing-api/src/Itinero.API/bin/Debug/netcoreapp2.0/Itinero.API.dll                                                          
                                                                                               
Build succeeded.                                                                                    
    0 Warning(s)                                                                                                      
    0 Error(s)                                                                                                                     
                                                                                                                                    
Time Elapsed 00:00:02.88                                                                       
Using launch settings from /[...]/routing-api/src/Itinero.API/Properties/launchSettings.json...                                                      
[Bootstrapper] information - Loading all routerdb's from path: /[...]/routing-api/src/Itinero.API/data                                               
[Bootstrapper] information - Loading instance netherlands from: /[...]/routing-api/src/Itinero.API/data/netherlands.c.cf.routerdb                    
                                                                                                                                                                                              
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)                                                                                                                                                          
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()                                   
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)                                                                                                      
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)                                                                                                 
   --- End of inner exception stack trace ---                                                                                                                                                  
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)                                                                                                    
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)                                                                                         
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)                                                                                                               at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()                                                                                                                                    
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)                       
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)                                                                                                   
   at Itinero.API.Program.Main(String[] args) in /[...]/routing-api/src/Itinero.API/Program.cs:line 45
```

Tried to fix it by manually installing the missing package, as suggested somewhere else, with 

```
dotnet add src/Itinero.API/Itinero.API.csproj package 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv'`
```

Now the error is different:

```
$ ./run.sh
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core                                
Copyright (C) Microsoft Corporation. All rights reserved.                                      

  Restoring packages for /[...]/routing-api/src/Itinero.API/Itinero.API.csproj...                                                                     
  Restore completed in 441.63 ms for /[...]/routing-api/src/Itinero.API/Itinero.API.csproj.                                                           
  Itinero.API -> /[...]/routing-api/src/Itinero.API/bin/Debug/netcoreapp2.0/Itinero.API.dll                                                           

Build succeeded.                               
    0 Warning(s)                               
    0 Error(s)                                 

Time Elapsed 00:00:02.97                       
Using launch settings from /[...]/routing-api/src/Itinero.API/Properties/launchSettings.json...                                                       

Unhandled Exception: System.TypeLoadException: Method 'ConfigureAppConfiguration' in type 'Microsoft.AspNetCore.Hosting.WebHostBuilder' from assembly 'Microsoft.AspNetCore.Hosting, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

Any ideas?
